@extends('admin')

@section('title')
User's Info | {{$user->first_name." ". $user->last_name}}
@endsection

@section('content')
<h2>User's Information</h2> <br>
<div class="ui two column middle aligned very relaxed stackable grid">
  <div class="column">
<div class="ui card"> 
  <div class="image">
    <img src="/images/{{$user->image}}">
  </div>
  <div class="content">
    <a class="header">{{$user->first_name." ". $user->last_name}}</a>
    <div class="meta">
 
    @if($user->code != 'autogenerated account')
      <span class="date">Joined {{$user->created_at->diffForHumans()}}</span>
    @else
      This is an autogenerated account for testing purposes.
    @endif
    </div>
    <div class="description">
    <b> Username: {{$user->username}} </b>
    </div>
  </div>
  <div class="extra content">
    <a>
      <i class="user icon"></i>
      @if($user->role == 1)
      Role: Member
      @elseif($user->role == 2)
      Role: Head User
      @else
      Role: Administrator
      @endif

    </a>
  </div>  
</div>
</div>
<div class="column">
<div class="ui statistics">
  <div class="statistic">
    <div class="value">
      {{$file_count}}
    </div>
    <div class="label">
      Files
    </div>
  </div>
  <div class="statistic">
    <div class="value">
    {{$post_count}}
    </div>
    <div class="label">
      Posts
    </div>
  </div>
  <div class="statistic">
    <div class="value">
    {{$group_count}}
    </div>
    <div class="label">
      Groups
    </div>
  </div>
</div>
</div>
</div>
<br>
<br>
<br>
<br>



@endsection