<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateUsersTable extends Migration
{

    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('first_name');
            $table->string('middle_name')->nullable();
            $table->string('last_name');
            $table->boolean('active');
            $table->integer('role');
            $table->string('email')->unique();
            $table->string('username')->unique();
            $table->string('password');
            $table->string('code')->nullable();
            $table->string('image')->default('avatar.png');
            $table->string('devicetoken')->nullable();
            $table->rememberToken();
            $table->timestamps();
        });

         DB::table('users')->insert(
        array(
            array(
                'first_name' =>'Rafael Ray',
                'middle_name' =>'Bautista',
                'last_name' =>'Castro',
                'email' => 'rafael.raybcastro@gmail.com',
                'active'=>true,
                'role' => 2,
                'username' => 'rbcastro',
                'password' => bcrypt('dong7777'),
                'code' => 'autogenerated account',
                
            ),

            array(
                'first_name' =>'Stefanie Joy',
                'middle_name' =>'Fuentes',
                'last_name' =>'See',
                'email' => 'stefaniejoysee@gmail.com',
                'active'=>true,
                'role' => 1,
                'username' => 'sfsee',
                'password'=> bcrypt('dong7777'),
                'code' => 'autogenerated account',
                
            ),
                array(
                'first_name' =>'Roy',
                'middle_name' =>'Bautista',
                'last_name' =>'Castro',
                'email' => 'puroycastro@gmail.com',
                'active'=>true,
                'role' => 1,
                'username' => 'royboi', 
                'password'=> bcrypt('puroy'),
                'code' => 'autogenerated account',
            ),

                 array(
                'first_name' =>'Juan Carlos',
                'middle_name' =>'Bautista',
                'last_name' =>'Castro',
                'email' => 'caloycastro@gmail.com',
                'active'=>true,
                'role' => 1,
                'username' => 'loloy',
                'password'=> bcrypt('caloy'),
                'code' => 'autogenerated account',
                
            ),

                            array(
                'first_name' =>'Tasha',
                'middle_name' =>'Bautista',
                'last_name' =>'Castro',
                'email' => 'tashacastro@gmail.com',
                'active'=>true,
                'role' => 1,
                'username' => 'mamagirl',
                'password'=> bcrypt('tasha'),
                'code' => 'autogenerated account',
                
            ),
                            array(
                'first_name' =>'Vannesa',
                'middle_name' =>'Bautista',
                'last_name' =>'Castro',
                'email' => 'vannesacastro@gmail.com',
                'active'=>true,
                'role' => 1,
                'username' => 'babygirl',
                'password'=> bcrypt('vannesa'),
                'code' => 'autogenerated account',
                
            ),
                            array(
                'first_name' =>'Pancho',
                'middle_name' =>'Bautista',
                'last_name' =>'Castro',
                'email' => 'panchocastro@gmail.com',
                'active'=>true,
                'role' => 1,
                'username' => 'panchoboi',
                'password'=> bcrypt('pancho'),
                'code' => 'autogenerated account',
                
            ),

                            array(
                'first_name' =>'Wansoi',
                'middle_name' =>'Bautista',
                'last_name' =>'Castro',
                'email' => 'wansoicastro@gmail.com',
                'active'=>true,
                'role' => 1,
                'username' => 'wansoi',
                'password'=> bcrypt('wansoi'),
                'code' => 'autogenerated account',
                
            ),

            array(
                'first_name' =>'Raf',
                'middle_name' =>'Bau',
                'last_name' =>'Castro',
                'email' => 'raf@admin.com',
                'active'=>true,
                'role' => 3,
                'username' => 'admin1',
                'password'=> bcrypt('dong7777'),
                'code' => 'autogenerated account',
                
            ),

            array(
                'first_name' =>'Stef',
                'middle_name' =>'Fue',
                'last_name' =>'See',
                'email' => 'stef@admin.com',
                'active'=>true,
                'role' => 3,
                'username' => 'admin2',
                'password'=> bcrypt('dong7777'),
                'code' => 'autogenerated account',
                
            ),

            array(
                'first_name' =>'Boi',
                'middle_name' =>'',
                'last_name' =>'See',
                'email' => 'annika@admin.com',
                'active'=>true,
                'role' => 3,
                'username' => 'admin3',
                'password'=> bcrypt('dong7777'),
                'code' => 'autogenerated account',
                
            ),


        )
    );
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}
